---
title: "similarity-slider"
output: html_document
date: "2024-11-12"
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
pacman::p_load(tidyverse,
               ggforce,
               conflicted,
               here,
               cowplot,
               lme4,
               lmerTest,
               effects,
               performance,
               purrr,
               readr,
               igraph,
               corrplot,
               Hmisc,
               ggraph,
               tidygraph,
               visNetwork,
               scales)

library(plotly) #for some reason this never loads via pacman
walk(c("select", "filter", "rename", "mutate", "summarize", "count", "arrange"), ~ conflict_prefer(.x, "dplyr"))
conflicts_prefer(plotly::layout)
theme_set(theme_bw())
sessionInfo()

```

# Read data

```{r}
directory_path <- here("code", "analysis", "pilot", "data-slider")
file_paths <- list.files(path = directory_path, full.names = TRUE)
d <- map_df(file_paths, ~ read_csv(.x) %>% mutate(filename = basename(.x)))

```
# Exclusions

- for now, leaving undone
- need to decide if we will exclude for failing all 3 attention checks or at least 1

```{r}
#d %>%
  # mutate(correct = case_when(trial_id == "attention_check_1" & response == 0 ~ TRUE,
  #                            trial_id == "attention_check_3" & response == 100 ~ TRUE,
  #                            trial_id == "attention_check_2" & ( response > 60 & response < 80 )
  #                            ~ TRUE,
  #                            TRUE ~ correct)) %>% 
  #group_by(mturk_participant_id) %>%
  #filter(all(correct | is.na(correct))) %>% #remove 2 participants who failed at least 1 att check
  #ungroup()
```

# Tidy data

```{r}
# retain relevant columns
df <- d %>% 
  relocate(mturk_participant_id, .before = "trial_id") %>% 
  select("mturk_participant_id", "trial_id", "rt", "response", 
         "itemA", "itemB", "categoryA", "categoryB") %>% 
  filter(!trial_id %in% c("practice_feedback", "demographics_survey", 
                          "consent", "practice_round")) %>% 
  mutate(response = as.numeric(response)) %>% 
  filter(!str_detect(trial_id, "^attention_check_")) %>% 
  mutate(type = ifelse(categoryA == categoryB, "within domain", "across domain")) %>% 
  mutate(categoryA = case_when(categoryA == "physiological" ~ "bio", 
                               categoryA == "cognitive" ~ "cog", 
                               TRUE ~ "act"),
         categoryB = case_when(categoryB == "physiological" ~ "bio", 
                               categoryB == "cognitive" ~ "cog", 
                               TRUE ~ "act")) %>% 
  mutate(category_pairs = str_c(categoryA, categoryB, sep = "-"))  %>% 
  group_by(category_pairs) %>%
  mutate(category_pair_means = mean(response)) %>% #reordering category labels
  ungroup() %>%
  mutate(category_pairs = fct_reorder(category_pairs, 
                                      category_pair_means, .desc = TRUE)) %>% 
  mutate(item_pairs = str_c(itemA, itemB, sep = "-")) %>%
  group_by(item_pairs) %>%
  mutate(item_pair_means = round(mean(response), 0))# %>%
  #ungroup() %>%  #reordering item labels
  #mutate(item_pairs = fct_reorder(item_pairs, item_pair_means, .desc = TRUE)) 


df_means <- df %>%
  select(itemA:item_pair_means) %>%
  unique() %>%
  mutate(mean_centered = (item_pair_means/100 - .5)*2)
  
df_pair_means <- df_means %>%
  ungroup() %>%
  select(itemA, itemB, mean_centered) 

df_pair_means$itemA <- factor(df_pair_means$itemA, levels=c("see something",
                                      "hear something",
                                      "choose what to do",
                                      "remember something",
                                      "think about something",
                                      "reach for something",
                                      "sit down",
                                      "jump up and down",
                                      "kick something",
                                      "take a walk",
                                      "feel tired",
                                      "feel hungry",
                                      "feel scared",
                                      "feel pain",
                                      "feel sick"))

df_pair_means$itemB <- factor(df_pair_means$itemB, levels=c("see something",
                                      "hear something",
                                      "choose what to do",
                                      "remember something",
                                      "think about something",
                                      "reach for something",
                                      "sit down",
                                      "jump up and down",
                                      "kick something",
                                      "take a walk",
                                      "feel tired",
                                      "feel hungry",
                                      "feel scared",
                                      "feel pain",
                                      "feel sick"))

```

# Plots

## Plot corrplot

```{r}
pair_matrix <- xtabs(mean_centered ~ itemA + itemB, data = df_pair_means)

corrplot(pair_matrix, 
         method="color",
         tl.col	= "black")
```




## Plot pair averages 

```{r}
df %>%
  ggplot(aes(x = item_pairs, y = response)) +
  geom_point(alpha = .3) +
  geom_point(stat = "summary", fun = "mean", size = 1, shape = 23, 
             fill = "white", color = "black") +
  theme(axis.text.x = element_text(angle = 90, size = 3))

```

## Plot category means 

```{r}
df %>%
  ggplot(aes(x = category_pairs, y = response, color = type)) +
  geom_jitter(alpha = .4, size = 3, width = .1) +
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", width = 0.2, color = "black") +
  geom_point(stat = "summary", fun = "mean", size = 3, shape = 23, 
             fill = "white", color = "black") +
  theme_bw() +
  theme(
    axis.text = element_text(size = 12),
    axis.text.x = element_text(angle = 90)) +
  labs(x = "causation type")

```

## Plot domain averages

```{r}
df %>%
  ggplot(aes(x = type, y = response)) +
  geom_jitter(alpha = .4, size = 3, color = "skyblue", width = .1) +
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar",width = 0.2) +
  geom_point(stat = "summary", fun = "mean", size = 3, shape = 23, fill = "white") +
  theme_bw() +
  theme(axis.text = element_text(size = 12)) +
  labs(x = "causation type") 

```


# feedback

it seems some folks were interpreting it as causation
```{r}
df_feedback <- d %>% 
  select(feedback) %>% 
  drop_na(feedback)

cat(df_feedback$feedback, sep = "\n\n")

```

