---
title: "study 2"
output: html_document
date: "2024-10-28"
---

# ReadMe

This is the analysis for study 3 of the MBC project, alias the counterfactual study.  
The study had N = XX, and subjects saw two conditions: Intervention and Similarity, with 15 trials per condition.
The question: 

# Set options

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
pacman::p_load(tidyverse, 
               lme4, 
               here, 
               patchwork, 
               cowplot, 
               viridis, 
               effects, 
               gt,
               webshot2,
               knitr,
               performance)
sessionInfo()

```

# Read data


```{r, warnings = FALSE}
base_path <- here("code", "analysis", "pilot")
data_path <- paste0(base_path, "/data-counterfactual_1/pilot")
data_path_2 <- paste0(base_path, "/data-counterfactual_1/pilot2")


desired_order <- c("see something", "hear something", "choose what to do", 
                   "remember something", "think about something", "reach for something", 
                   "sit down", "jump up and down", "kick something", "take a walk", 
                   "get tired", "become hungry", "feel scared", "experience pain", "get sick")

d <- read_csv(paste0(data_path, "/2025-03-27_19-18-32_undefined.csv"))

file_paths <- list.files(path = data_path_2, pattern = "^2025-", full.names = TRUE)

d <- imap_dfr(file_paths, ~ {
  read_csv(.x, col_types = cols(response = col_character())) %>%
    mutate(
      filename = basename(.x),
      subject_id = paste0("subj_", str_pad(.y, 2, pad = "0"))
    )}) %>%
  select(-c(mturk_participant_id, mturk_assignment_id, mturk_project_id)) %>%
  relocate(subject_id, .before = "success")


```


```{r}
d %>% 
  filter(condition %in% c("counterfactual", "similarity")) 

d %>% 
  select(response, response_value)

d %>% 
  count(subject_id, condition)
```



# Wrangle data

```{r}
 subjects_to_exclude <- d %>%
  filter(grepl("attention_check", condition)) %>% 
  filter(attn_correct == "yes") %>% 
  pull(subject_id) %>% 
  unique()

dat <- d %>% 
  # filter(!subject_id %in% subjects_to_exclude) %>% 
  # filter(subject_id %in% subjects_to_exclude) %>% #exclude 1 subject who failed attn check
  filter(condition %in% c("counterfactual", "similarity")) %>%
  mutate(response = as.factor(response)) %>% 
  mutate(condition = as.factor(condition)) %>% 
  rowwise() %>%
  mutate(option = case_when(
    grepl(causal_itemA, response_value) ~ "causal",
    grepl(similar_itemA, response_value) ~ "similar",
    TRUE ~ "other"
  )) %>% 
  # mutate(condition = case_when(
  #   condition == "similarity" ~ "inference",
  #   TRUE ~ condition
  # )) %>% 
  ungroup() %>% 
  select(
    # subject_id, 
    condition, itemB, causal_itemA, similar_itemA, response_value) %>% 
  mutate(causal_itemA = factor(causal_itemA, levels = desired_order),
         similar_itemA = factor(similar_itemA, levels = desired_order),
         itemB = factor(itemB, levels = desired_order)) %>% 
  mutate(domain_itemB = case_when(itemB == "hear something" ~ "mind", #labels for first item of pair
                                 itemB == "choose what to do" ~ "mind",
                                 itemB == "remember something" ~ "mind",
                                 itemB == "think about something" ~ "mind",
                                 itemB == "see something" ~ "mind",
                                 itemB == "reach for something" ~ "action",
                                 itemB == "sit down" ~ "action", 
                                 itemB == "jump up and down" ~ "action",
                                 itemB == "kick something" ~ "action",
                                 itemB == "take a walk" ~ "action",
                                 itemB == "get tired" ~ "bio", 
                                 itemB == "become hungry" ~ "bio",
                                 itemB == "feel scared"~ "bio",
                                 itemB == "experience pain"~ "bio",
                                 itemB == "get sick"~ "bio"),
         domain_causalitemA = case_when(causal_itemA == "hear something" ~ "mind", 
                                 causal_itemA == "choose what to do" ~ "mind",
                                 causal_itemA == "remember something" ~ "mind",
                                 causal_itemA == "think about something" ~ "mind",
                                 causal_itemA == "see something" ~ "mind",
                                 causal_itemA == "reach for something" ~ "action",
                                 causal_itemA == "sit down" ~ "action", 
                                 causal_itemA == "jump up and down" ~ "action",
                                 causal_itemA == "kick something" ~ "action",
                                 causal_itemA == "take a walk" ~ "action",
                                 causal_itemA == "get tired" ~ "bio", 
                                 causal_itemA == "become hungry" ~ "bio",
                                 causal_itemA == "feel scared"~ "bio",
                                 causal_itemA == "experience pain"~ "bio",
                                 causal_itemA == "get sick"~ "bio"),
          domain_similaritemA = case_when(similar_itemA == "hear something" ~ "mind", 
                                 similar_itemA == "choose what to do" ~ "mind",
                                 similar_itemA == "remember something" ~ "mind",
                                 similar_itemA == "think about something" ~ "mind",
                                 similar_itemA == "see something" ~ "mind",
                                 similar_itemA == "reach for something" ~ "action",
                                 similar_itemA == "sit down" ~ "action", 
                                 similar_itemA == "jump up and down" ~ "action",
                                 similar_itemA == "kick something" ~ "action",
                                 similar_itemA == "take a walk" ~ "action",
                                 similar_itemA == "get tired" ~ "bio", 
                                 similar_itemA == "become hungry" ~ "bio",
                                 similar_itemA == "feel scared"~ "bio",
                                 similar_itemA == "experience pain"~ "bio",
                                 similar_itemA == "get sick"~ "bio")) 


```


```{r}
dat %>% 
  ggplot(aes(x = condition, y = response_value)) +
  geom_point() +
  # geom_jitter(width  = .3) +
  stat_summary(fun = mean, geom = "point", color = "red") +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = .2) +
  theme_bw()
```


```{r}

```














